name: Build & Sign iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Decode signing certificate and provisioning profile
        run: |
          mkdir -p ~/certs
          echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > ~/certs/dist.p12
          echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/certs/profile.mobileprovision

      - name: Install Apple certificate
        run: |
          security create-keychain -p "temp_password" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp_password" build.keychain
          security import ~/certs/dist.p12 -k build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ~/certs/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build iOS App with code signing
        env:
          CI: true
          APP_NAME: Runner
          DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
          CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.BUNDLE_ID }}
        run: |
          flutter build ios --release \
            --build-name=1.0.0 \
            --build-number=1 \
            --no-codesign

      - name: Export IPA using xcodebuild
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath $PWD/build/Runner.xcarchive \
                     archive \
                     DEVELOPMENT_TEAM="${{ secrets.TEAM_ID }}" \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}" \
                     PROVISIONING_PROFILE_SPECIFIER="${{ secrets.BUNDLE_ID }}"

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportPath $PWD/build/ios/ipa \
                     -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: SignedRunner.ipa
          path: ios/build/ios/ipa/*.ipa
          if-no-files-found: error
          retention-days: 7

      - name: Upload to TestFlight (optional)
        uses: apple-actions/upload-testflight@v1
        with:
          app-path: ios/build/ios/ipa/*.ipa
          apple-id: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          app-password: ${{ secrets.APP_SPECIFIC_PASSWORD }}
