name: Build iOS IPA (no signing)

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS release (no signing)
        run: flutter build ios --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../Runner.ipa
          ls -lh ../Runner.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: Runner.ipa
          path: build/ios/Runner.ipa
          if-no-files-found: error

